name: Publish release candidate

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
  workflow_dispatch:

jobs:
  build_and_publish:
    permissions:
      id-token: write
      contents: read
      packages: write
    env:
      APP_NAME: ds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get tag name
        id: tag-name
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: configure-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
        env: ${{ secrets.NPM_REGISTRY_TOKEN }}
      - name: Get node version
        id: node
        run: |
          echo "version=$(node -v)" >> $GITHUB_OUTPUT

      - name: Get node_modules cache
        uses: actions/cache@v3.0.2
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn build
      - run: yarn publish --tag ${{ steps.tag-name.outputs.tag }}
